/* //device/libs/telephony/ril_commands.h
**
** Copyright 2006, The Android Open Source Project
**
** Licensed under the Apache License, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
**
**     http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
*/
    {RIL_OEM_REQUEST_BASE, NULL}, // RIL_OEM_REQUEST_BASE should be defined as 10000 in ril.h
    {10001, NULL},
    {RIL_REQUEST_GET_CELL_BROADCAST_CONFIG, NULL},
    {10003, NULL},
    {10004, NULL},
    {RIL_REQUEST_SEND_ENCODED_USSD, NULL},
    {RIL_REQUEST_SET_PDA_MEMORY_STATUS, NULL},
    {RIL_REQUEST_GET_PHONEBOOK_STORAGE_INFO, NULL},
    {RIL_REQUEST_GET_PHONEBOOK_ENTRY, NULL},
    {RIL_REQUEST_ACCESS_PHONEBOOK_ENTRY, NULL},
    {RIL_REQUEST_DIAL_VIDEO_CALL, NULL},
    {RIL_REQUEST_CALL_DEFLECTION, NULL},
    {RIL_REQUEST_READ_SMS_FROM_SIM, NULL},
    {RIL_REQUEST_USIM_PB_CAPA, NULL},
    {RIL_REQUEST_LOCK_INFO, NULL},
    {10015, NULL},
    {RIL_REQUEST_DIAL_EMERGENCY, NULL},
    {RIL_REQUEST_GET_STOREAD_MSG_COUNT, NULL},
    {RIL_REQUEST_STK_SIM_INIT_EVENT, NULL},
    {RIL_REQUEST_GET_LINE_ID, NULL},
    {RIL_REQUEST_SET_LINE_ID, NULL},
    {RIL_REQUEST_GET_SERIAL_NUMBER, NULL},
    {RIL_REQUEST_GET_MANUFACTURE_DATE_NUMBER, NULL},
    {RIL_REQUEST_GET_BARCODE_NUMBER, NULL},
    {RIL_REQUEST_UICC_GBA_AUTHENTICATE_BOOTSTRAP, NULL},
    {RIL_REQUEST_UICC_GBA_AUTHENTICATE_NAF, NULL},
    {RIL_REQUEST_SIM_TRANSMIT_BASIC, NULL},
    {RIL_REQUEST_SIM_OPEN_CHANNEL, NULL},
    {RIL_REQUEST_SIM_CLOSE_CHANNEL, NULL},
    {RIL_REQUEST_SIM_TRANSMIT_CHANNEL, NULL},
    {RIL_REQUEST_SIM_AUTH, NULL},
    {RIL_REQUEST_PS_ATTACH, NULL},
    {RIL_REQUEST_PS_DETACH, NULL},
    {RIL_REQUEST_ACTIVATE_DATA_CALL, NULL},
    {RIL_REQUEST_CHANGE_SIM_PERSO, NULL},
    {RIL_REQUEST_ENTER_SIM_PERSO, NULL},
    {RIL_REQUEST_GET_TIME_INFO, NULL},
    {RIL_REQUEST_OMADM_SETUP_SESSION, NULL},
    {RIL_REQUEST_OMADM_SERVER_START_SESSION, NULL},
    {RIL_REQUEST_OMADM_CLIENT_START_SESSION, NULL},
    {RIL_REQUEST_OMADM_SEND_DATA, NULL},
    {RIL_REQUEST_CDMA_GET_DATAPROFILE, NULL},
    {RIL_REQUEST_CDMA_SET_DATAPROFILE, NULL},
    {RIL_REQUEST_CDMA_GET_SYSTEMPROPERTIES, NULL},
    {RIL_REQUEST_CDMA_SET_SYSTEMPROPERTIES, NULL},
    {RIL_REQUEST_SEND_SMS_COUNT, NULL},
    {RIL_REQUEST_SEND_SMS_MSG, NULL},
    {RIL_REQUEST_SEND_SMS_MSG_READ_STATUS, NULL},
    {RIL_REQUEST_MODEM_HANGUP, NULL},
    {RIL_REQUEST_SET_SIM_POWER, NULL},
    {RIL_REQUEST_SET_PREFERRED_NETWORK_LIST, NULL},
    {RIL_REQUEST_GET_PREFERRED_NETWORK_LIST, NULL},
    {RIL_REQUEST_HANGUP_VT, NULL},
